# version: '3.7'

# services:
#   db:
#     image: postgres:12.0-alpine
#     volumes:
#       - postgres_data:/var/lib/postgresql/data/
#     environment:
#       - POSTGRES_USER=library_bot
#       - POSTGRES_PASSWORD=12345
#       - POSTGRES_DB=library_bot
#     expose:
#       - "5432"
#     ports:
#       - "5432:5432"
#   web:
#     depend_on:
#       - db

# volumes:
#   postgres_data:
version: '3.9'

services:
  db:
    image: postgres:15.2
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 6432:5432
  web:
    build:
      context: .
    env_file:
      - .env
    volumes:
      - ./storage:/app/storage
    depends_on:
      - db
    ports:
      - 8002:8002

volumes:
  postgres_data:
